spring: 
  application:
    name: consumer-service
  
server:
  context-path: /consumer
  port: 7002

eureka:
  client:
    service-url:
    #单点配置
    #defaultZone: http://eureka1:8001/eureka/
    #高可用配置
      defaultZone: http://eureka1:8001/eureka/,http://eureka2:8002/eureka/